import type { Post } from '../types/graphql.ts';
export const MOCK_POSTS: Post[] = [
  {
    id: '1',
    author: 'Elon Musk',
    profileImageUrl: 'https://i.pravatar.cc/150?u=elonmusk',
    content:
      '🚀 Mars mission update: Starship is looking incredible! The engineering team has made breakthrough improvements to the heat shield design. We\'re targeting early 2026 for the first crewed mission to Mars. The future of humanity as a multi-planetary species is closer than ever!',
    likes: 89420,
    comments: 12300,
    reposts: 15600,
    views: 2800000,
    timestamp: '2025-08-28T10:30:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1446776653964-20c1d3a81b06?w=800&h=600&fit=crop&crop=center',
    isReply: false,
    parentPostId: null,
  },
  {
    id: '2',
    author: 'Michelle Obama',
    profileImageUrl: 'https://i.pravatar.cc/150?u=michelleobama',
    content:
      '📚 There\'s nothing quite like the power of a good book to transport you, teach you, and transform you. I\'m thrilled to announce that our latest @penguinrandomhouse initiative will provide 100,000 free books to underserved communities across America. Education changes everything. 💛',
    likes: 156700,
    comments: 8900,
    reposts: 42300,
    views: 3200000,
    timestamp: '2025-08-28T09:15:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&h=600&fit=crop&crop=center',
    isReply: false,
    parentPostId: null,
  },
  {
    id: '3',
    author: 'Elon Musk',
    profileImageUrl: 'https://i.pravatar.cc/150?u=elonmusk',
    content:
      'Tesla Model Y just became the best-selling car in the world! 🏆 Not just best-selling electric car, but best-selling car overall. This is a major milestone for sustainable transport. The future is electric and it\'s happening faster than anyone predicted.',
    likes: 67890,
    comments: 5600,
    reposts: 8900,
    views: 1900000,
    timestamp: '2025-08-28T08:45:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&h=600&fit=crop&crop=center',
    isReply: false,
    parentPostId: null,
  },
  {
    id: '4',
    author: 'Michelle Obama',
    profileImageUrl: 'https://i.pravatar.cc/150?u=michelleobama',
    content:
      'Spending the morning with young leaders from around the world at the @ObamaFoundation Democracy Forum. Their passion, creativity, and commitment to building a better world gives me so much hope. The future is in great hands! 🌟',
    likes: 98500,
    comments: 4200,
    reposts: 18700,
    views: 2100000,
    timestamp: '2025-08-28T07:30:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=800&h=600&fit=crop&crop=center',
    isReply: false,
    parentPostId: null,
  },
  {
    id: '5',
    author: 'Tim Cook',
    profileImageUrl: 'https://i.pravatar.cc/150?u=timcook',
    content:
      'Privacy is a fundamental human right. Apple\'s latest iOS update includes even stronger privacy protections, giving users more control over their data than ever before. We believe privacy and great user experiences can coexist. 🛡️ #PrivacyMatters',
    likes: 45600,
    comments: 3400,
    reposts: 7800,
    views: 1200000,
    timestamp: '2025-08-28T06:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=800&h=600&fit=crop&crop=center',
    isReply: false,
    parentPostId: null,
  },
  {
    id: '6',
    author: 'Oprah Winfrey',
    profileImageUrl: 'https://i.pravatar.cc/150?u=oprahwinfrey',
    content:
      'Just finished reading \'The Seven Husbands of Evelyn Hugo\' and I am OBSESSED! 📖✨ This book had me laughing, crying, and everything in between. Taylor Jenkins Reid has created something truly magical. Adding this to my book club list immediately!',
    likes: 78900,
    comments: 12100,
    reposts: 23400,
    views: 2600000,
    timestamp: '2025-08-28T05:30:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop&crop=center',
    isReply: false,
    parentPostId: null,
  },
  {
    id: '7',
    author: 'Satya Nadella',
    profileImageUrl: 'https://i.pravatar.cc/150?u=satyanadella',
    content:
      'AI is not about replacing human intelligence—it\'s about amplifying it. Microsoft\'s latest AI tools are helping doctors diagnose diseases faster, teachers personalize learning, and scientists solve climate challenges. Technology at its best serves humanity. 🤖💡',
    likes: 34200,
    comments: 2800,
    reposts: 5600,
    views: 890000,
    timestamp: '2025-08-28T04:15:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=600&fit=crop&crop=center',
    isReply: false,
    parentPostId: null,
  },
  {
    id: '8',
    author: 'Elon Musk',
    profileImageUrl: 'https://i.pravatar.cc/150?u=elonmusk',
    content:
      'Neuralink patient update: Our first human patient can now control a computer cursor just by thinking! This is still early days, but the implications for people with paralysis are profound. We\'re literally giving people their digital freedom back. 🧠💻',
    likes: 125600,
    comments: 15600,
    reposts: 28900,
    views: 4100000,
    timestamp: '2025-08-28T03:45:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&h=600&fit=crop&crop=center',
    isReply: false,
    parentPostId: null,
  },
  {
    id: '9',
    author: 'Michelle Obama',
    profileImageUrl: 'https://i.pravatar.cc/150?u=michelleobama',
    content:
      'Barack surprised me with a dance lesson today! 💃🕺 After 30+ years together, he still knows how to make me laugh and try new things. Here\'s to never stopping learning, growing, and dancing through life together!',
    likes: 234500,
    comments: 18700,
    reposts: 45600,
    views: 5200000,
    timestamp: '2025-08-28T02:20:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800&h=600&fit=crop&crop=center',
    isReply: false,
    parentPostId: null,
  },
  {
    id: '10',
    author: 'Bill Gates',
    profileImageUrl: 'https://i.pravatar.cc/150?u=billgates',
    content:
      'Incredible progress on malaria prevention! Our foundation\'s latest report shows a 50% reduction in malaria cases across sub-Saharan Africa over the past decade. When we work together with science and compassion, we can solve humanity\'s greatest challenges. 🌍',
    likes: 56700,
    comments: 4300,
    reposts: 12100,
    views: 1800000,
    timestamp: '2025-08-28T01:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1584515933487-779824d29309?w=800&h=600&fit=crop&crop=center',
    isReply: false,
    parentPostId: null,
  },
  {
    id: '11',
    author: 'Ryan Reynolds',
    profileImageUrl: 'https://i.pravatar.cc/150?u=ryanreynolds',
    content:
      'Deadpool 3 filming wrapped! 🎬 I can\'t say much (Disney lawyers are scary), but I will say this: Hugh Jackman still looks better in the suit than me and I\'m not even a little bit okay with it. Thanks for an incredible journey, everyone! 💛❤️',
    likes: 187600,
    comments: 34500,
    reposts: 67800,
    views: 3800000,
    timestamp: '2025-08-28T00:30:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1489599162759-41e1db9cf72b?w=800&h=600&fit=crop&crop=center',
    isReply: false,
    parentPostId: null,
  },
  {
    id: '12',
    author: 'Elon Musk',
    profileImageUrl: 'https://i.pravatar.cc/150?u=elonmusk',
    content:
      'Working on something fun with the Boring Company. Hint: it involves flame throwers and s\'mores. Sometimes the best engineering solutions are also the most delicious. 🔥🏗️',
    likes: 78900,
    comments: 8900,
    reposts: 12400,
    views: 2100000,
    timestamp: '2025-08-27T23:45:00Z',
    imageUrl: null,
    isReply: false,
    parentPostId: null,
  },
  {
    id: '13',
    author: 'A. R. Rahman',
    profileImageUrl: 'https://i.pravatar.cc/150?u=arrahman',
    content:
      'Music is the language of the spirit. It opens the secret of life bringing peace, abolishing strife.',
    likes: 99999,
    comments: 9999,
    reposts: 9999,
    views: 999999,
    timestamp: '2025-08-27T22:30:00Z',
    imageUrl: null,
    isReply: false,
    parentPostId: null,
  },
  {
    id: '14',
    author: 'Sundar Pichai',
    profileImageUrl: 'https://i.pravatar.cc/150?u=sundarpichai',
    content:
      'A person who is happy is not because everything is right in his life, he is happy because his attitude towards everything in his life is right.',
    likes: 88888,
    comments: 8888,
    reposts: 8888,
    views: 888888,
    timestamp: '2025-08-27T21:15:00Z',
    imageUrl: null,
    isReply: false,
    parentPostId: null,
  },
  {
    id: '15',
    author: 'Satya Nadella',
    profileImageUrl: 'https://i.pravatar.cc/150?u=satyanadella',
    content:
      'Our industry does not respect tradition - it only respects innovation.',
    likes: 77777,
    comments: 7777,
    reposts: 7777,
    views: 777777,
    timestamp: '2025-08-27T20:00:00Z',
    imageUrl: null,
    isReply: false,
    parentPostId: null,
  },
  {
    id: '16',
    author: 'Deepika Padukone',
    profileImageUrl: 'https://i.pravatar.cc/150?u=deepikapadukone',
    content:
      'I am a woman, I am a leader, I am a wife, I am a friend, I am a daughter. I am proud of all these roles. I am not defined by any one of them.',
    likes: 66666,
    comments: 6666,
    reposts: 6666,
    views: 666666,
    timestamp: '2025-08-27T18:45:00Z',
    imageUrl: null,
    isReply: false,
    parentPostId: null,
  },
  {
    id: '17',
    author: 'Priyanka Chopra Jonas',
    profileImageUrl: 'https://i.pravatar.cc/150?u=priyankachopra',
    content:
      'Don’t try to be someone else. Be yourself. And know that what you have to offer is unique.',
    likes: 55555,
    comments: 5555,
    reposts: 5555,
    views: 555555,
    timestamp: '2025-08-27T17:30:00Z',
    imageUrl: null,
    isReply: false,
    parentPostId: null,
  },
  {
    id: '18',
    author: 'Shah Rukh Khan',
    profileImageUrl: 'https://i.pravatar.cc/150?u=shahrukhkhan',
    content:
      'Success is not a good teacher, failure makes you humble.',
    likes: 44444,
    comments: 4444,
    reposts: 4444,
    views: 444444,
    timestamp: '2025-08-27T16:15:00Z',
    imageUrl: null,
    isReply: false,
    parentPostId: null,
  },
  {
    id: '19',
    author: 'Virat Kohli',
    profileImageUrl: 'https://i.pravatar.cc/150?u=viratkohli',
    content:
      'I like to be myself, and I don\'t pretend. For instance, I don\'t dress up for occasions; I am what I am.',
    likes: 33333,
    comments: 3333,
    reposts: 3333,
    views: 333333,
    timestamp: '2025-08-27T15:00:00Z',
    imageUrl: null,
    isReply: false,
    parentPostId: null,
  },
  {
    id: '20',
    author: 'Rohit Sharma',
    profileImageUrl: 'https://i.pravatar.cc/150?u=rohitsharma',
    content:
      'I am not a person who can be happy with just one hundred. I want to score two hundred, three hundred.',
    likes: 22222,
    comments: 2222,
    reposts: 2222,
    views: 222222,
    timestamp: '2025-08-27T13:45:00Z',
    imageUrl: null,
    isReply: false,
    parentPostId: null,
  },
  {
    id: '21',
    author: 'M.S. Dhoni',
    profileImageUrl: 'https://i.pravatar.cc/150?u=msdhoni',
    content:
      'I believe in giving more than 100% on the field, and I don\'t really worry about the result if there\'s great commitment on the field. That\'s a victory for me.',
    likes: 11111,
    comments: 1111,
    reposts: 1111,
    views: 111111,
    timestamp: '2025-08-27T12:30:00Z',
    imageUrl: null,
    isReply: false,
    parentPostId: null,
  },
  {
    id: '22',
    author: 'Sachin Tendulkar',
    profileImageUrl: 'https://i.pravatar.cc/150?u=sachintendulkar',
    content:
      'People throw stones at you and you convert them into milestones.',
    likes: 10000,
    comments: 1000,
    reposts: 1000,
    views: 100000,
    timestamp: '2025-08-27T11:15:00Z',
    imageUrl: null,
    isReply: false,
    parentPostId: null,
  },
  {
    id: '23',
    author: 'Rahul Dravid',
    profileImageUrl: 'https://i.pravatar.cc/150?u=rahuldravid',
    content:
      'I have failed at times, and I have succeeded at other times. But I have never given up, and I have never stopped trying.',
    likes: 9000,
    comments: 900,
    reposts: 900,
    views: 90000,
    timestamp: '2025-08-27T10:00:00Z',
    imageUrl: null,
    isReply: false,
    parentPostId: null,
  },
  {
    id: '24',
    author: 'Sourav Ganguly',
    profileImageUrl: 'https://i.pravatar.cc/150?u=souravganguly',
    content:
      'As a sportsman, you always want to be the best. That is the nature of the beast.',
    likes: 8000,
    comments: 800,
    reposts: 800,
    views: 80000,
    timestamp: '2025-08-27T08:45:00Z',
    imageUrl: null,
    isReply: false,
    parentPostId: null,
  },
  {
    id: '25',
    author: 'Anil Kumble',
    profileImageUrl: 'https://i.pravatar.cc/150?u=anilkumble',
    content:
      'I have been a fighter and I have been a winner. I am not a quitter.',
    likes: 7000,
    comments: 700,
    reposts: 700,
    views: 70000,
    timestamp: '2025-08-27T07:30:00Z',
    imageUrl: null,
    isReply: false,
    parentPostId: null,
  },
  {
    id: '26',
    author: 'Javagal Srinath',
    profileImageUrl: 'https://i.pravatar.cc/150?u=javagalsrinath',
    content:
      'I have always believed that if you want to be the best, you have to work the hardest.',
    likes: 5000,
    comments: 500,
    reposts: 500,
    views: 50000,
    timestamp: '2025-08-27T05:00:00Z',
    imageUrl: null,
    isReply: false,
    parentPostId: null,
  },
  {
    id: '27',
    author: 'Venkatesh Prasad',
    profileImageUrl: 'https://i.pravatar.cc/150?u=venkateshprasad',
    content:
      'I am a very aggressive person. I am a very emotional person. I am a very sensitive person.',
    likes: 4000,
    comments: 400,
    reposts: 400,
    views: 40000,
    timestamp: '2025-08-27T03:45:00Z',
    imageUrl: null,
    isReply: false,
    parentPostId: null,
  },
  {
    id: '28',
    author: 'B.K.S. Iyengar',
    profileImageUrl: 'https://i.pravatar.cc/150?u=bksiyengar',
    content:
      'Yoga is a light, which once lit, will never dim. The better your practice, the brighter the flame.',
    likes: 3000,
    comments: 300,
    reposts: 300,
    views: 30000,
    timestamp: '2025-08-27T02:30:00Z',
    imageUrl: null,
    isReply: false,
    parentPostId: null,
  },
  {
    id: '29',
    author: 'Jagadish Vasudev (Sadhguru)',
    profileImageUrl: 'https://i.pravatar.cc/150?u=sadhguru',
    content:
      'The only way out is in.',
    likes: 2000,
    comments: 200,
    reposts: 200,
    views: 20000,
    timestamp: '2025-08-27T01:15:00Z',
    imageUrl: null,
    isReply: false,
    parentPostId: null,
  }
];

export const MOCK_POSTS_POOL: Post[] = [
  {
    id: '31',
    author: 'Taylor Swift',
    profileImageUrl: 'https://i.pravatar.cc/150?u=taylorswift',
    content: 'Folklore is out now. I poured all of my whims, dreams, fears, and musings into it. I hope you love it as much as I do.',
    likes: 1200000,
    comments: 150000,
    reposts: 300000,
    views: 10000000,
    timestamp: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1587731556938-cd3c865b5c8b?w=800&h=600&fit=crop&crop=center',
    isReply: false,
    parentPostId: null,
  },
  {
    id: '32',
    author: 'Cristiano Ronaldo',
    profileImageUrl: 'https://i.pravatar.cc/150?u=cristianoronaldo',
    content: 'Hard work always pays off. Great win today! #HalaMadrid',
    likes: 2500000,
    comments: 200000,
    reposts: 500000,
    views: 20000000,
    timestamp: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1587731556938-cd3c865b5c8b?w=800&h=600&fit=crop&crop=center',
    isReply: false,
    parentPostId: null,
  },
  {
    id: '33',
    author: 'Ariana Grande',
    profileImageUrl: 'https://i.pravatar.cc/150?u=arianagrande',
    content: 'thank u, next is out now. i love you.',
    likes: 1800000,
    comments: 180000,
    reposts: 400000,
    views: 15000000,
    timestamp: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1587731556938-cd3c865b5c8b?w=800&h=600&fit=crop&crop=center',
    isReply: false,
    parentPostId: null,
  },
  {
    id: '34',
    author: 'Dwayne Johnson',
    profileImageUrl: 'https://i.pravatar.cc/150?u=dwaynejohnson',
    content: 'Blood, sweat, and respect. The first two you give, the last one you earn. #IronParadise',
    likes: 3000000,
    comments: 250000,
    reposts: 600000,
    views: 25000000,
    timestamp: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1587731556938-cd3c865b5c8b?w=800&h=600&fit=crop&crop=center',
    isReply: false,
    parentPostId: null,
  },
  {
    id: '35',
    author: 'Kylie Jenner',
    profileImageUrl: 'https://i.pravatar.cc/150?u=kyliejenner',
    content: 'new @kyliecosmetics collection dropping this friday! can’t wait for you guys to see it.',
    likes: 4000000,
    comments: 300000,
    reposts: 700000,
    views: 30000000,
    timestamp: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1587731556938-cd3c865b5c8b?w=800&h=600&fit=crop&crop=center',
    isReply: false,
    parentPostId: null,
  },
  {
    id: '36',
    author: 'Lionel Messi',
    profileImageUrl: 'https://i.pravatar.cc/150?u=lionelmessi',
    content: 'Gracias a todos por el apoyo. Seguimos trabajando para conseguir nuestros objetivos. Força Barça!',
    likes: 3500000,
    comments: 280000,
    reposts: 650000,
    views: 28000000,
    timestamp: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1587731556938-cd3c865b5c8b?w=800&h=600&fit=crop&crop=center',
    isReply: false,
    parentPostId: null,
  },
  {
    id: '37',
    author: 'Selena Gomez',
    profileImageUrl: 'https://i.pravatar.cc/150?u=selenagomez',
    content: 'Rare is out now. So happy to finally share this with you all.',
    likes: 2800000,
    comments: 220000,
    reposts: 550000,
    views: 22000000,
    timestamp: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1587731556938-cd3c865b5c8b?w=800&h=600&fit=crop&crop=center',
    isReply: false,
    parentPostId: null,
  },
  {
    id: '38',
    author: 'Justin Bieber',
    profileImageUrl: 'https://i.pravatar.cc/150?u=justinbieber',
    content: 'Yummy out now. #Yummy',
    likes: 2200000,
    comments: 200000,
    reposts: 450000,
    views: 18000000,
    timestamp: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1587731556938-cd3c865b5c8b?w=800&h=600&fit=crop&crop=center',
    isReply: false,
    parentPostId: null,
  },
  {
    id: '39',
    author: 'Beyoncé',
    profileImageUrl: 'https://i.pravatar.cc/150?u=beyonce',
    content: 'Black Is King is out now. A labor of love. My hope for this film is that it shifts the global perception of the word Black.',
    likes: 5000000,
    comments: 400000,
    reposts: 800000,
    views: 35000000,
    timestamp: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1587731556938-cd3c865b5c8b?w=800&h=600&fit=crop&crop=center',
    isReply: false,
    parentPostId: null,
  },
  {
    id: '40',
    author: 'Neymar Jr',
    profileImageUrl: 'https://i.pravatar.cc/150?u=neymarjr',
    content: 'Obrigado a todos pelo apoio. Seguimos fortes. #PSG',
    likes: 2000000,
    comments: 150000,
    reposts: 400000,
    views: 15000000,
    timestamp: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1587731556938-cd3c865b5c8b?w=800&h=600&fit=crop&crop=center',
    isReply: false,
    parentPostId: null,
  }
];